### ISSUE TITLE
Serial Bluetooth on Android 9 not working

### ISSUE THREAD

**Issue by Joe7M** [smallbasic/SmallBASIC#242]
Hi Chris,

my tablet is still running on Android 9. When trying to connect to a HC-06 Bluetooth module using `android.openBluetooth("SB")` I get the error message `LIB:ANDROID: Not permitted`. I use the following SB program:

```
import android
bt = android.openBluetooth("SmallBASIC")
print bt.description()
bt.close
```

Using the app "Serial Bluetooth Terminal" the HC-06 works fine.

A reason could be, that the android permissions are not set correctly. In this article: https://developer.android.com/develop/connectivity/bluetooth/bt-permissions#declare they write, that for Android 11 and lower additionally a `BLUETOOTH` permission needs to be set.

Maybe it helps. Otherwise it is time to get a new tablet (and or mobile phone).

Best regards, Joerg

**Comment by chrisws** [comment]
Hi Joerg,

I've just pushed an update in the testing channel. It will take a few hours before it hopefully appears on your tablet.

Hope this works !

Cheers,
Chris

**Comment by Joe7M** [comment]
I tested the new version, but unfortunately it still don't work.  I'm not experienced in Android development. I can imagine, that in your code the permission check

````java
 if (checkPermission(activity, Manifest.permission.BLUETOOTH_CONNECT)) {
      requestPermission(activity, Manifest.permission.BLUETOOTH_CONNECT);
      throw createIoException(activity, R.string.PERMISSION_ERROR);
    }
````

will throw the exception on Android 9, because some of the permissions don't exist.

I had a look, how it is done in the SerialBluetoothTerminal [github](https://github.com/kai-morich/SimpleBluetoothTerminal/blob/master/app/src/main/java/de/kai_morich/simple_bluetooth_terminal/BluetoothUtil.java). it seems they check, which Android version is used:

````java
static boolean hasPermissions(Fragment fragment, ActivityResultLauncher<String> requestPermissionLauncher) {
        if(Build.VERSION.SDK_INT < Build.VERSION_CODES.S)
            return true;
...
````

If you think this is not worth to fix, because Android 9 is too old, I would be fine. Depends in the end how complicated things get.

Best regards, Joerg

**Comment by chrisws** [comment]
Thanks for the feedback, I'll take another look over the weekend.

**Comment by Joe7M** [comment]
Thank you, it works now. I have to grand permission once and then I can communicate with the HC-06 module.
